import Head from "next/head";
import SideBar from "@/components/SideBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wellcome to Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SideBar />
      </main>
    </>
  );
}
